import Head from 'next/head';

import CartRoot from '../../components/Cart';
import AppWrapper from '../../components/layouts/AppWrapper';
import CONST_VALUE from '../../data/constants';
import { NextPageWithLayout } from '../../types';

const Cart: NextPageWithLayout = () => (
  <div>
    <Head>
      <title>{CONST_VALUE.pageTitle.cart}</title>
      <meta name="Cart" content="Generated by Participle Plus" />
    </Head>
    <CartRoot />
  </div>
);

Cart.getLayout = page => <AppWrapper>{page}</AppWrapper>;
export default Cart;
