import { Box } from '@mantine/core';
import React from 'react';

import Head from 'next/head';
import CONST_VALUE from '../../data/constants';
import CheckoutRoot from '../../components/Checkout';
import AppWrapper from '../../components/layouts/AppWrapper';
import { NextPageWithLayout } from '../../types';

const CheckoutPage: NextPageWithLayout = () => (
  <div>
    <Head>
      <title>{CONST_VALUE.pageTitle.checkout}</title>
      <meta name="description" content="Generated by Sayanta" />
    </Head>
    <Box className="mb-20">
      <CheckoutRoot />
    </Box>
  </div>
);

CheckoutPage.getLayout = page => <AppWrapper>{page}</AppWrapper>;
export default CheckoutPage;
