import { Box, Button, CheckIcon, Radio, Stepper, Text, rem } from '@mantine/core';
import { IconUserCheck, IconMailOpened } from '@tabler/icons-react';
import React, { useState } from 'react';

import { useCreateOrder } from 'src/api/queries/order.queries';
import { useRouter } from 'next/router';
import { useSelector } from 'react-redux';
import { RootState } from 'src/redux/store';
import Head from 'next/head';
import CONST_VALUE from 'src/data/constants';
import AppWrapper from '../../components/layouts/AppWrapper';
import { NextPageWithLayout } from '../../types';

const CheckoutPage: NextPageWithLayout = () => {
  const [active, setActive] = useState(0);
  const [paymentType, setPaymentType] = useState('COD');
  const cartData = useSelector((state: RootState) => state.cart);
  const createOrder = useCreateOrder();
  const router = useRouter();

  const handleOrderBooking = () => {
    const productInfo = cartData.items.map(item => ({ productId: item._id, quantity: 1 }));
    createOrder.mutate(
      {
        total: 200,
        address: 'Something',
        products: productInfo,
      },
      {
        onSuccess: async () => {
          router.push('/');
        },
      },
    );
  };
  return (
    <div>
      <Head>
        <title>{CONST_VALUE.pageTitle.checkout}</title>
        <meta name="description" content="Generated by Sayanta" />
      </Head>
      <Box>
        <Stepper
          className="mb-8"
          color="dark"
          active={active}
          onStepClick={setActive}
          iconPosition="left"
          classNames={{
            step: 'p-0',
            steps: 'items-center',
            separator: 'mx-[-0.4rem] translate-y-[-1rem]',
          }}
        >
          <Stepper.Step
            classNames={{
              step: 'flex-col',
              stepBody: 'm-0 py-2',
            }}
            label="Shipping"
            icon={<IconUserCheck style={{ width: rem(18), height: rem(18) }} />}
          >
            <Box className="border-b-[1px] py-5">
              <Box className="flex flex-row justify-between">
                <Box className="flex flex-col">
                  <Text>Estimated Total</Text>
                  <Text>${cartData.total}</Text>
                </Box>
                <Box className="flex border-2 border-dark-grey px-5 items-center">
                  {cartData.items.length} {cartData.items.length > 1 ? 'items' : 'item'}
                </Box>
              </Box>
            </Box>
            <Box className="border-b-[1px] border-dark-grey pt-5 pb-2 mt-5">
              <Box className="flex flex-row justify-between">
                <Box className="flex flex-col">
                  <Text>Shipping Address</Text>
                </Box>
              </Box>
            </Box>
            <Box className="border-b-[1px] border-dark-grey pt-5 pb-2 mt-5">
              <Box className="flex flex-row justify-between">
                <Box className="flex flex-col">
                  <Text>Shipping Methods</Text>
                </Box>
              </Box>
            </Box>
            <Box className="border-b-[1px] border-dark-grey pt-5 pb-2 mt-5">
              <Box className="flex flex-row justify-between">
                <Box className="flex flex-col">
                  <Text>In-Store Pickup</Text>
                </Box>
              </Box>
            </Box>
            <Button
              onClick={() => setActive(1)}
              variant="filled"
              color="dark"
              fullWidth
              className="mb-8 h-auto p-4 text-md"
            >
              Next
            </Button>
          </Stepper.Step>
          <Stepper.Step
            classNames={{
              step: 'flex-col justify-center',
              stepBody: 'm-0 py-2',
            }}
            label="Payments"
            icon={<IconMailOpened style={{ width: rem(18), height: rem(18) }} />}
          >
            <Box>
              <Box className="border-b-[1px] py-5">
                <Box className="flex flex-row justify-between">
                  <Box className="flex flex-col">
                    <Text>Estimated Total</Text>
                    <Text>$156.00</Text>
                  </Box>
                  <Box className="flex border-2 border-dark-grey px-5 items-center">14 items</Box>
                </Box>
              </Box>
              <Box className="border-b-[1px] border-dark-grey pt-5 pb-2 mt-5">
                <Box className="flex flex-row justify-between">
                  <Box className="flex flex-col">
                    <Text>Payment Method</Text>
                  </Box>
                </Box>
              </Box>
              <Box>
                <Radio
                  icon={CheckIcon}
                  color="dark"
                  name="COD"
                  value="COD"
                  onChange={() => setPaymentType('COD')}
                  className="border-b-[1px] border-dark-grey "
                  checked={paymentType === 'COD'}
                  label={
                    <Box className="flex flex-row justify-between">
                      <Box className="flex flex-col">
                        <Text>Cash on Delivery</Text>
                      </Box>
                    </Box>
                  }
                />
                <Radio
                  color="dark"
                  name="Razorpay"
                  checked={paymentType === 'Razorpay'}
                  icon={CheckIcon}
                  value="Razorpay"
                  onChange={() => setPaymentType('Razorpay')}
                  label={
                    <Box className="flex flex-row justify-between">
                      <Box className="flex flex-col">
                        <Text>Payment Method</Text>
                      </Box>
                    </Box>
                  }
                />
              </Box>
              <Box>
                <Button onClick={handleOrderBooking} fullWidth color="dark" className="h-auto p-4">
                  Continue
                </Button>
              </Box>
            </Box>
          </Stepper.Step>
        </Stepper>
      </Box>
    </div>
  );
};

CheckoutPage.getLayout = page => <AppWrapper>{page}</AppWrapper>;
export default CheckoutPage;
