import { Box, Text } from '@mantine/core';
import Head from 'next/head';
import { getOrders } from 'src/api/queries/order.queries';
import AppWrapper from 'src/components/layouts/AppWrapper';
import CONST_VALUE from 'src/data/constants';
import { NextPageWithLayout } from 'src/types';

const Orders: NextPageWithLayout = () => {
  const orders = getOrders();
  return (
    <div>
      <Head>
        <title>{CONST_VALUE.pageTitle.orders}</title>
        <meta name="Orders" content="Generated by Sayanta" />
      </Head>
      <Box>{orders.data && orders.data.map(item => <Text>{item.total}</Text>)}</Box>
    </div>
  );
};

Orders.getLayout = page => <AppWrapper>{page}</AppWrapper>;
export default Orders;
